CREATE TABLE [Passenger]
(

);

CREATE TABLE [Checks]
(

);

CREATE TABLE [Train_Stat]
(
	[TNum] INTEGER NOT NULL UNIQUE,
	[TName] VCHAR(100) NOT NULL,
	[BookDate] DATETIME,
	[GSeatsAvail] INTEGER,
	[GSeatsOcc] INTEGER,
	[PSeatsAvail] INTEGER,
	[PSeatsOcc] INTEGER,
	[Location] VCHAR(160) NOT NULL,
	[Platform] VCHAR(160),
	CONSTRAINT [PK_TStat] PRIMARY KEY ([TNum], [TName]),
	FOREIGN KEY  ([TName]) REFERENCES [Train] ([Name])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE [Train]
(

);

CREATE TABLE [Train_Avail]
(

);

CREATE TABLE [Train_Dest]
(
	[DTrainID] INTEGER NOT NULL,
	[TDest] VCHAR(160) NOT NULL,
	CONSTRAINT [PK_TDest] PRIMARY KEY ([DTrainID], [TDest]),
	FOREIGN KEY ([DTrainID]) REFERENCES [Train] ([TrainID])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
